defmodule PalmSync4Mac.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :calendar_event,
                     [
                       :calendar_name,
                       :end_date,
                       :invitees,
                       :last_modified,
                       :location,
                       :notes,
                       :start_date,
                       :title,
                       :url
                     ],
                     name: "calendar_event_unique_event_index"
                   )

    create unique_index(
             :calendar_event,
             [:title, :start_date, :end_date, :notes, :url, :location, :invitees, :calendar_name],
             name: "calendar_event_unique_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :calendar_event,
                     [
                       :title,
                       :start_date,
                       :end_date,
                       :notes,
                       :url,
                       :location,
                       :invitees,
                       :calendar_name
                     ],
                     name: "calendar_event_unique_event_index"
                   )

    create unique_index(
             :calendar_event,
             [
               :calendar_name,
               :end_date,
               :invitees,
               :last_modified,
               :location,
               :notes,
               :start_date,
               :title,
               :url
             ],
             name: "calendar_event_unique_event_index"
           )
  end
end