defmodule PalmSync4Mac.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:palm, primary_key: false) do
      add :last_sync_status, :text
      add :last_synced, :date
      add :name, :text, null: false
      add :id, :bigint, null: false, primary_key: true
    end

    create table(:calendar_event, primary_key: false) do
      add :apple_event_id, :text
      add :deleted, :boolean
      add :invitees, {:array, :text}
      add :calendar_name, :text, null: false
      add :last_modified, :utc_datetime
      add :location, :text
      add :url, :text
      add :notes, :text
      add :end_date, :utc_datetime, null: false
      add :start_date, :utc_datetime, null: false
      add :title, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :calendar_event,
             [
               :title,
               :start_date,
               :end_date,
               :notes,
               :url,
               :location,
               :invitees,
               :last_modified,
               :calendar_name
             ],
             name: "calendar_event_unique_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :calendar_event,
                     [
                       :title,
                       :start_date,
                       :end_date,
                       :notes,
                       :url,
                       :location,
                       :invitees,
                       :last_modified,
                       :calendar_name
                     ],
                     name: "calendar_event_unique_event_index"
                   )

    drop table(:calendar_event)

    drop table(:palm)
  end
end