defmodule PalmSync4Mac.Repo.Migrations.EntityAndDevice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:calendar, primary_key: false) do
      add :end_date, :bigint, null: false
      add :start_date, :bigint, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:calendar)
  end
end