defmodule PalmSync4Mac.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:palm_user, primary_key: false) do
      add :last_sync_date, :utc_datetime, null: false
      add :successful_sync_date, :utc_datetime
      add :last_sync_pc, :text
      add :viewer_id, :text
      add :user_id, :text, null: false
      add :password, :text, null: false
      add :username, :text, null: false
      add :password_length, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:palm_user, [:user_id], name: "palm_user_unique_event_index")
  end

  def down do
    drop_if_exists unique_index(:palm_user, [:user_id], name: "palm_user_unique_event_index")

    drop table(:palm_user)
  end
end