defmodule PalmSync4Mac.Repo.Migrations.AddUniqueUserIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Only the palm_user unique index is generated here by hand: this repo's
    # committed migrations carry the `_dev` suffix, and this ash_sqlite version
    # treats every `_dev` migration as an uncommitted draft — a named
    # `generate_migrations` run therefore rolled them down, deleted them, and
    # produced a consolidated replacement that also dropped the join-table
    # migration. The op below is byte-identical to the incremental migration
    # the generator's --dry-run produced for the :unique_user_id identity.
    create unique_index(:palm_user, [:user_id], name: "palm_user_unique_user_id_index")
  end

  def down do
    drop_if_exists unique_index(:palm_user, [:user_id], name: "palm_user_unique_user_id_index")
  end
end
