defmodule PalmSync4Mac.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:calendar_event) do
      add :alarms_seconds, {:array, :bigint}, null: false, default: []
    end
  end

  def down do
    alter table(:calendar_event) do
      remove :alarms_seconds
    end
  end
end