defmodule PalmSync4Mac.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:palm_user, primary_key: false) do
      add(:last_sync_date, :bigint, null: false)
      add(:successful_sync_date, :bigint)
      add(:last_sync_pc, :bigint, null: false)
      add(:viewer_id, :bigint, null: false)
      add(:user_id, :bigint, null: false)
      add(:password, :text)
      add(:username, :text, null: false)
      add(:password_length, :bigint, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create(unique_index(:palm_user, [:username], name: "palm_user_unique_event_index"))

    create table(:calendar_event, primary_key: false) do
      add(:version, :bigint, null: false)
      add(:apple_event_id, :text)
      add(:deleted, :boolean)
      add(:invitees, {:array, :text})
      add(:calendar_name, :text, null: false)
      add(:last_modified, :utc_datetime, null: false)
      add(:location, :text)
      add(:url, :text)
      add(:notes, :text)
      add(:end_date, :utc_datetime, null: false)
      add(:start_date, :utc_datetime, null: false)
      add(:title, :text, null: false)
      add(:source, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create(
      unique_index(:calendar_event, [:apple_event_id], name: "calendar_event_unique_event_index")
    )

    create table(:ek_calendar_datebook_sync_status, primary_key: false) do
      add(
        :calendar_event_id,
        references(:calendar_event,
          column: :id,
          name: "ek_calendar_datebook_sync_status_calendar_event_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(
        :palm_user_id,
        references(:palm_user,
          column: :id,
          name: "ek_calendar_datebook_sync_status_palm_user_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:last_sync_success, :boolean, null: false)
      add(:last_synced_version, :bigint, null: false)
      add(:last_synced, :utc_datetime, null: false)
      add(:rec_id, :bigint, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create(
      unique_index(:ek_calendar_datebook_sync_status, [:palm_user_id, :calendar_event_id],
        name: "ek_calendar_datebook_sync_status_unique_device_event_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:calendar_event, [:apple_event_id], name: "calendar_event_unique_event_index")
    )

    drop_if_exists(
      unique_index(
        :ek_calendar_datebook_sync_status,
        [:palm_user_id, :calendar_event_id],
        name: "ek_calendar_datebook_sync_status_unique_device_event_index"
      )
    )

    drop(
      constraint(
        :ek_calendar_datebook_sync_status,
        "ek_calendar_datebook_sync_status_palm_user_id_fkey"
      )
    )

    drop(
      constraint(
        :ek_calendar_datebook_sync_status,
        "ek_calendar_datebook_sync_status_calendar_event_id_fkey"
      )
    )

    drop(table(:ek_calendar_datebook_sync_status))
    drop(table(:calendar_event))
    drop_if_exists(unique_index(:palm_user, [:username], name: "palm_user_unique_event_index"))
    drop(table(:palm_user))
  end
end
